version: '3'
services:
  mysql:
    container_name: "autoo-mysql-${APP_ID}"
    image: "mysql:8.0.19"
    platform: linux/x86_64
    ports:
      - "13306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: autoo123456
      MYSQL_DATABASE: autoo
      MYSQL_USER: autoo
      MYSQL_PASSWORD: 123456
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/logs
      - ./service/db:/docker-entrypoint-initdb.d/
    command:
      --lower-case-table-names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    networks:
      extnetwork:
        ipv4_address: "10.88.88.101"
    restart: always
networks:
  extnetwork:
    name: "autoo-networks-${APP_ID}"
    ipam:
      config:
        - subnet: "10.88.88.0/24"
          gateway: "10.88.88.1"