version: '3'

services:
#  autoo-web:
#      container_name: "autoo-web-${APP_ID}"
#      build:
#        context: .
#        dockerfile: ./Dockerfile
#      ports:
#        - "8099:80"
#      networks:
#        extnetwork:
#          ipv4_address: 10.66.66.9
#      restart: unless-stopped

  nginx:
    container_name: "autoo-nginx-${APP_ID}"
    image: "nginx:alpine"
    ports:
      - "${APP_PORT}:80"
      - "${APP_SSL_PORT:-}:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
#      - ./public:/var/www/public
    networks:
      extnetwork:
        ipv4_address: 10.66.66.11
    restart: unless-stopped

  fileview:
    container_name: "autoo-fileview-${APP_ID}"
    image: "kuaifan/fileview:4.2.0-SNAPSHOT-RC25"
    environment:
      KK_CONTEXT_PATH: "/fileview"
      KK_OFFICE_PREVIEW_SWITCH_DISABLED: true
      KK_FILE_UPLOAD_ENABLED: true
      KK_MEDIA: "mp3,wav,mp4,mov,avi,wmv"
    networks:
      extnetwork:
        ipv4_address: 10.66.66.3
    restart: unless-stopped
  drawio-webapp:
    container_name: "autoo-drawio-webapp-${APP_ID}"
    image: "jgraph/drawio:20.8.20"
    volumes:
      - ./docker/drawio/webapp/index.html:/usr/local/tomcat/webapps/draw/index.html
      - ./docker/drawio/webapp/stencils:/usr/local/tomcat/webapps/draw/stencils
      - ./docker/drawio/webapp/js/app.min.js:/usr/local/tomcat/webapps/draw/js/app.min.js
      - ./docker/drawio/webapp/js/croppie/croppie.min.css:/usr/local/tomcat/webapps/draw/js/croppie/croppie.min.css
      - ./docker/drawio/webapp/js/diagramly/ElectronApp.js:/usr/local/tomcat/webapps/draw/js/diagramly/ElectronApp.js
    networks:
      extnetwork:
        ipv4_address: 10.66.66.4
    depends_on:
      - drawio-export
    restart: unless-stopped
  drawio-export:
    container_name: "autoo-drawio-export-${APP_ID}"
    image: "kuaifan/export-server:0.0.1"
    networks:
      extnetwork:
        ipv4_address: 10.66.66.5
    volumes:
      - ./docker/drawio/export/fonts:/usr/share/fonts/drawio
    restart: unless-stopped
  minder:
    container_name: "autoo-minder-${APP_ID}"
    image: "kuaifan/minder:0.1.3"
    ports:
      - "8100:80"
    networks:
      extnetwork:
        ipv4_address: 10.66.66.6
    restart: unless-stopped
  office:
    container_name: "dootask-office-${APP_ID}"
    image: "onlyoffice/documentserver:7.5.1.1"
    volumes:
      - ./docker/office/logs:/var/log/onlyoffice
      - ./docker/office/data:/var/www/onlyoffice/Data
      - ./docker/office/resources/require.js:/var/www/onlyoffice/documentserver/web-apps/vendor/requirejs/require.js
      - ./docker/office/resources/documenteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/css/app.css
      - ./docker/office/resources/documenteditor/mobile/css/964.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/mobile/css/964.css
      - ./docker/office/resources/presentationeditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/main/resources/css/app.css
      - ./docker/office/resources/presentationeditor/mobile/css/612.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/mobile/css/612.css
      - ./docker/office/resources/spreadsheeteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/css/app.css
      - ./docker/office/resources/spreadsheeteditor/mobile/css/887.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/mobile/css/887.css
    environment:
      JWT_SECRET: ${APP_KEY}
    networks:
      extnetwork:
        ipv4_address: 10.66.66.7
    restart: unless-stopped
networks:
  extnetwork:
    name: "autoo-networks-${APP_ID}"
    ipam:
      config:
        - subnet: "10.66.66.0/24"
          gateway: "10.66.66.1"
