version: '3'

services:
  web:
    container_name: "autoo-web-${APP_ID}"
    image: "autoopm-web:latest"
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - dev_env
    depends_on:
      - autoo-api
  autoo-api:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: "autoo-api-${APP_ID}"
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8081:8081"
    volumes:
      - ./service/data:/home/task/data
    restart: always
    networks:
      - dev_env
  nginx:
    container_name: "autoo-nginx-${APP_ID}"
    image: "nginx:alpine"
    ports:
      - "${APP_PORT}:80"
      - "443"
    volumes:
      - ./docker/nginx-local:/etc/nginx/conf.d
#      - ./ui/public:/var/www/public
#      - ./ui/dist:/var/www/dist
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - dev_env
    restart: unless-stopped
  #  fileview:
#    container_name: "autoo-fileview-${APP_ID}"
#    image: "kuaifan/fileview:4.2.0-SNAPSHOT-RC25"
#    environment:
#      KK_CONTEXT_PATH: "/fileview"
#      KK_OFFICE_PREVIEW_SWITCH_DISABLED: true
#      KK_FILE_UPLOAD_ENABLED: true
#      KK_MEDIA: "mp3,wav,mp4,mov,avi,wmv"
#    networks:
#      extnetwork:
#        ipv4_address: 10.66.66.3
#    restart: unless-stopped
  drawio-webapp:
    container_name: "autoo-drawio-webapp-${APP_ID}"
    image: "jgraph/drawio:20.8.20"
    ports:
      - "8102:8080"
    volumes:
      - ./docker/drawio/webapp/index.html:/usr/local/tomcat/webapps/draw/index.html
      - ./docker/drawio/webapp/stencils:/usr/local/tomcat/webapps/draw/stencils
      - ./docker/drawio/webapp/js/app.min.js:/usr/local/tomcat/webapps/draw/js/app.min.js
      - ./docker/drawio/webapp/js/croppie/croppie.min.css:/usr/local/tomcat/webapps/draw/js/croppie/croppie.min.css
      - ./docker/drawio/webapp/js/diagramly/ElectronApp.js:/usr/local/tomcat/webapps/draw/js/diagramly/ElectronApp.js
    networks:
      - dev_env
    depends_on:
      - drawio-export
    restart: unless-stopped
  drawio-export:
    container_name: "autoo-drawio-export-${APP_ID}"
    image: "kuaifan/export-server:0.0.1"
    networks:
      - dev_env
    volumes:
      - ./docker/drawio/export/fonts:/usr/share/fonts/drawio
    restart: unless-stopped
  minder:
    container_name: "autoo-minder-${APP_ID}"
    image: "kuaifan/minder:0.1.3"
    ports:
      - "8101:80"
    networks:
      - dev_env
    restart: unless-stopped
  office:
    container_name: "autoo-office-${APP_ID}"
    image: "onlyoffice/documentserver:latest"
    volumes:
      - ./docker/office/logs:/var/log/onlyoffice
      - ./docker/office/data:/var/www/onlyoffice/Data
      - ./docker/office/resources/require.js:/var/www/onlyoffice/documentserver/web-apps/vendor/requirejs/require.js
      - ./docker/office/resources/documenteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/css/app.css
      - ./docker/office/resources/documenteditor/mobile/css/964.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/mobile/css/964.css
      - ./docker/office/resources/presentationeditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/main/resources/css/app.css
      - ./docker/office/resources/presentationeditor/mobile/css/612.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/mobile/css/612.css
      - ./docker/office/resources/spreadsheeteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/css/app.css
      - ./docker/office/resources/spreadsheeteditor/mobile/css/887.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/mobile/css/887.css
    environment:
      JWT_SECRET: ${APP_KEY}
    ports:
      - "8103:80"
    networks:
      - dev_env
    restart: unless-stopped
#  maxkb:
#    image: 1panel/maxkb
#    container_name: "autoo-maxkb-${APP_ID}"
#    ports:
#      - "8108:8080"
#    volumes:
#      - ./docker/maxkb:/var/lib/postgresql/data
#    networks:
#      extnetwork:
#        ipv4_address: 10.66.66.8
#    restart: always
#  wukongim:
#    container_name: "autoo-wukongim-${APP_ID}"
#    image: registry.cn-shanghai.aliyuncs.com/wukongim/wukongim:v1.2
#    ports:
#      - "5001:5001"
#      - "5100:5100"
#      - "5172:5172"
#      - "5200:5200"
#      - "5210:5210"
#      - "5300:5300"
#    volumes:
#      - ./docker/wukongim:/root/wukongim
#    networks:
#      extnetwork:
#        ipv4_address: 10.66.66.9
#    restart: always
  minio:
    container_name: "autoo-minio-${APP_ID}"
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: autoo    #管理后台用户名
      MINIO_SECRET_KEY: autoo123 #管理后台密码，最小8个字符
    volumes:
      - /docker/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /docker/minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    networks:
      - dev_env
    restart: always
  mysql:
    container_name: "autoo-mysql-${APP_ID}"
    image: "mysql:8.0.19"
    platform: linux/x86_64
    ports:
      - "33306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: autoo123456
      MYSQL_DATABASE: autoo
      MYSQL_USER: autoo
      MYSQL_PASSWORD: 123456
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/logs
      - ./service/db:/docker-entrypoint-initdb.d/
    command:
      --lower-case-table-names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    networks:
      - dev_env
    restart: always
networks:
  dev_env:
    driver: bridge
