FROM node:16-alpine
# Set working directory
WORKDIR /app

COPY . .
# 拷贝 .env.development 到镜像中
COPY .env.development .env
RUN yarn global add turbo
RUN yarn install
EXPOSE 5173
VOLUME [ "/app/node_modules", "/app/node_modules" ]
CMD ["yarn", "dev"]